"""Added ratings complex

Revision ID: 820445ee9863
Revises: 3ff6c29302bc
Create Date: 2024-11-12 12:40:03.332019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820445ee9863'
down_revision = '3ff6c29302bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numRatings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalRatings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avgRating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('avgRating')
        batch_op.drop_column('totalRatings')
        batch_op.drop_column('numRatings')

    # ### end Alembic commands ###
