name: Build and Deploy Documentation

on:
  push:
    branches:
      - develop  # Se ejecuta automáticamente con cada push a develop

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repositorio
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      # 3. Instalar dependencias de Sphinx
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme myst-parser

      # 4. Construir la documentación con Sphinx
      - name: Build documentation
        working-directory: docs
        run: |
          sphinx-build -b html ./source ./  # Generar la documentación directamente en /docs

      # 5. Hacer commit y push de la documentación generada
      - name: Commit updated documentation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/*
          git commit -m "docs(documentación): Documentación actualizada [skip ci]" || echo "No changes to commit"
          git push origin develop
