name: Validar descripción de Pull Request

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  validar-descripcion-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Validar título y descripción
        run: |
          descripcion="${{ github.event.pull_request.body }}"
          titulo="${{ github.event.pull_request.title }}"
          
          if [[ -z "$descripcion" ]]; then
            echo "Error: La descripción de la Pull Request está vacía."
            exit 1
          fi

          if [[ ${#descripcion} -gt 1000 ]]; then
            echo "Error: La descripción de la Pull Request supera los 1000 caracteres."
            exit 1
          fi

          if ! echo "$titulo" | grep -Eq '^(feat|fix|docs|style|refactor|test|chore|perf|build|ci)\([a-zA-Z0-9 _-]+\):\ .+'; then
            echo "Error: El título de la Pull Request no sigue el formato esperado."
            echo "Formato esperado: <tipo>(<módulo>): <descripción>"
            echo "Ejemplo válido: fix(workflows): Corrección en el pipeline de CI"
            echo "Título actual: '$titulo'"
            exit 1
          fi

          echo "La descripción y el título de la Pull Request son válidos."
