name: Deploy to Render

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'  
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Debug environment variables
        run: |
          echo "MARIADB_HOSTNAME=${{ secrets.MARIADB_HOSTNAME }}"
          echo "MARIADB_PORT=${{ secrets.MARIADB_PORT }}"
          echo "MARIADB_DATABASE=${{ secrets.MARIADB_DATABASE }}"
          echo "MARIADB_USER=${{ secrets.MARIADB_USER }}"
          echo "FLASK_ENV=${{ secrets.FLASK_ENV }}"

      - name: Test MySQL Connection
        run: |
          mysql -h ${{ secrets.MARIADB_HOSTNAME }} -P ${{ secrets.MARIADB_PORT }} -u${{ secrets.MARIADB_USER }} -p${{ secrets.MARIADB_PASSWORD }} -e "SHOW DATABASES;"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Populate Database
        env:
          FLASK_ENV: production
          MARIADB_HOSTNAME: ${{ secrets.MARIADB_HOSTNAME }}
          MARIADB_PORT: ${{ secrets.MARIADB_PORT }}
          MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
          MARIADB_USER: ${{ secrets.MARIADB_USER }}
          MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
        run: |
          flask db upgrade  
          flask db seed     

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$deploy_url"
