name: Run tests in parallel

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-xdist

    - name: Verify User Permissions
      run: |
        mysql -h 127.0.0.1 -u root -p'uvlhub_root_password' -e "
        GRANT ALL PRIVILEGES ON uvlhubdb_test.* TO 'uvlhub_user'@'%';
        FLUSH PRIVILEGES;"

    - name: Reset Database
      run: |
        mysql -h 127.0.0.1 -u root -p'uvlhub_root_password' -e "
        DROP DATABASE IF EXISTS uvlhubdb_test;
        CREATE DATABASE uvlhubdb_test;"

    - name: Apply Database Migrations
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
      run: |
        flask db upgrade

    - name: Run Tests
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
      run: |
        pytest -n auto app/modules/ --ignore-glob='*selenium*'

    - name: Save Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: .pytest_cache/
